apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiSGFwcHlkd2FyZiIsInBhc3N3b3JkIjoiZ2hwX0d3eDM4SWVieDRFV0RBd05QZW43cUI2clc2ZmxIMTBsRlc2bCIsImF1dGgiOiJTR0Z3Y0hsa2QyRnlaanBuYUhCZlIzZDRNemhKWldKNE5FVlhSRUYzVGxCbGJqZHhRalp5VnpabWJFZ3hNR3hHVnpacyJ9fX0=
kind: Secret
metadata:
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson
